# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Binyi Zhang
title: PhD candidate / Data Analytics
email: binyizhang@outlook.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: benyizhang
github_username:  benyizhang
linkedin_username: binyizhang

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://ies.fsv.cuni.cz/en/contacts/institute-members/69674391
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_photo.jpg
about_content: | # this will include new lines to allow paragraphs
  I am currently pursuing my Ph.D. at the Institute of Economic Studies, Charles University, where my research interest is in the fields of renewable energy, green finance, climate change, and credit rating.  I am fluent in Chinese, and English and actively developing my language skills in Slovak.
  
  My research primarily revolves around two key areas of study:
  - Green finance
  - Credit rating
  - Financial market analysis: stock, bond pricing

  The coding knowledge I am most familar with are: <mark>R</mark>, <mark>Stata</mark>, and <mark>snowflake SQL</mark>.

  
content:
  - title: Academic Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Geopolitical risk index
        link: 
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This project aims to assess the role of geopolitical risk index in determining the downgrade risk of corporate bond. 
        description: | # this will include new lines to allow paragraphs
          Some descriptions here: 
          

  - title: Woking Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: McKinsey & Company 
        link: https://www.mckinsey.com/
        # link_text: boringcompany.com
        sub_title: Data Analytics
        caption: July 2022 - Present
        description: | # this will include new lines to allow paragraphs
            My daily work at McKinsey invloves in following aspects:
            - Data clean: using <mark> Snowflake SQL </mark>, <mark> R </mark> and <mark> Python </mark> 
            - Data visualization: using <mark> Tableau </mark>  
            - Data analytics and reporting
            
        title: Charles University  
        link: https://www.mckinsey.com/
        # link_text: boringcompany.com
        sub_title: Teaching Assistant
        caption: September 2018 - Present
        description: | # this will include new lines to allow paragraphs
            Job responsibility:

        title: 4C Offshore 
        link: https://www.mckinsey.com/
        # link_text: boringcompany.com
        sub_title: Data Analyst
        caption: July 2022 - Present
        description: | # this will include new lines to allow paragraphs
            My daily work at McKinsey invloves in following aspects:


  - title: Education history # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Institute of Economic Studies, Charles University
        caption: 2018-Present
        sub_title: PhD candiate in Economics
        quote: >
          Probably, this the longset jounrey I have been through my entire life. Life is endless fight. 
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

        title: Institute of Economic Studies, Charles University
        caption: 2018-Present
        sub_title: PhD candiate in Economics
        quote: >
          Probably, this the longset jounrey I have been through my entire life. Life is endless fight. 
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
