# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Binyi Zhang
title: PhD candidate / Data Analytics
email: binyizhang@outlook.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: benyizhang
github_username:  benyizhang
linkedin_username: binyizhang

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://ies.fsv.cuni.cz/en/contacts/institute-members/69674391
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_photo.jpg
about_content: | # this will include new lines to allow paragraphs
  I am currently pursuing my Ph.D. at the Institute of Economic Studies, Charles University, where my research interest is in the fields of renewable energy, green finance, climate change, and credit rating.  I am fluent in Chinese, and English and actively developing my language skills in Slovak.
  
  My research primarily revolves around two key areas of study:
  - Green finance
  - Credit rating
  - Financial market analysis: stock, bond pricing

  The coding knowledge I am most familar with are: <mark>R</mark>, <mark>Stata</mark>, and <mark>snowflake SQL</mark>. I am progressing myself with <mark> Python </mark>. 
  Tech Stack:
  - Data modeling (<mark>Snowflake SQL</mark>)
  - Data visualisation and reporting (<mark>Tableau</mark>)
  - Advanced data analysis (<mark>R</mark>, <mark>Python</mark>, <mark>Stata</mark>) 

  

  
content:
  - title: Working Experience
    layout: list
    content:
      - layout: left
        title: "McKinsey & Company"
        link: "https://www.mckinsey.com/"
        sub_title: "Data Analytics"
        caption: "July 2022 - Present"
        description: |
          - Creating Tableau dashboards and interactive visualisation reflecting product and service performance at the firm level.
          - Applying advanced analytics tools and empirical methods to run data analysis using R, Python, SQL.
          - Data analysis and reporting to product and service teams to gain better access and insights from their data.

      - layout: left  # This dash is crucial; it signifies a new item in the list
        title: "Charles University"
        link: "https://ies.fsv.cuni.cz/"
        sub_title: "Teaching Assistant"
        caption: "September, 2018 - Present"
        description: |
          - Overseeing the design and devilry of seminar teaching materials.
          - Delivering weekly seminars.
          - Setting and grading student assignments.
          - Ensuring the maintenance of learning materials (Textbook, seminar slides, and suggested solutions) on the online learning environment site.

      - layout: left  # This dash is crucial; it signifies a new item in the list
        title: "Marcpoint Technology Ltd"
        link: "https://www.marcpoint.com/"
        sub_title: "Consumer Insight Analysts"
        caption: "January 2018 - June 2018"
        description: |
          - Data analysis using SQL, Excel and Python.
          - Consumer-based market information research and data analysis.
          - Customising solutions and supersessions for market promotions to enhance clients strategic marketing development and market competitiveness in Chinese Market.
          
      - layout: left  # This dash is crucial; it signifies a new item in the list
        title: "4C Offshore Ltd"
        link: "https://www.4coffshore.com/"
        sub_title: "Market Analysts"
        caption: "June 2016 - July 2017"
        description: |
          - Fundamental market research about the Chinese renewable energy market.
          - Customer relation management via phone calls and E-mails.
          - Estimating the industrial growth of Chinese offshore wind power based on given private databases.
          - Data analysis and result reporting on regular base. 
          - IBM Note and Microsoft Access Data Entry.
          
  - title: Education history 
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Institute of Economic Studies, Faculty of Social Sciences, Charles University
        - September 2018 - Present: PhD Candidate in Economics
      - University of East Anglia
        - September 2013 - July 2016: BSc. Business Finance and Economcis
        - September 2016 - September 2017: MSc. Economics

  - title: Working papers 
    layout: text
    content: | # this will include new lines to allow paragraphs
      Research work published at working paper: 
      - Janda K., Zhang B. (2019): "Renewable Energy Financial Modelling: A China Case Study", IES Working Papers 7/2019. IES FSV. Charles University.
      - Janda K., Zhang B. (2020). “The impact of renewable energy and technology innovation on Chinese carbon dioxide emissions”. FFA Working Paper 3/2020, FFA, University of Economics, Prague. • Janda K, Kortusova A, Zhang B (2022): "Green Bond Premiums in the Chinese Secondary Market", IES Working Papers 20/2022. IES FSV. Charles University.
      - Janda, K., Kortusova, A., and Zhang, B. (2022). "Estimation of green bond premiums in the Chinese secondary market", CAMA Working Papers 2022-38, Centre for Applied Macroeconomic Analysis, Crawford School of Public Policy, The Australian National University.
      - Janda, K., Kristoufek, L. and Zhang, B. (2022). “Return and volatility spillovers between Chinese and U.S. Clean Energy Related Stocks: Evidence from VAR-MGARCH estimations”, FFA Working Papers, 4, 2022.001.
      - Janda, K., Kristoufek, L. and Zhang, B. (2022)."Return and volatility spillovers between Chinese and US clean energy related stocks," CAMA Working Papers 2022-17, Centre for Applied Macroeconomic Analysis, Crawford School of Public Policy, The Australian National University.
  
  - title: Publications 
    layout: text
    content: | # this will include new lines to allow paragraphs
      Publications with impact factors:
      - Janda, K., Kocenda, E, Kortusova, A and Zhang, B (2022). Estimation of Green Bond Premiums in the Chinese Secondary Market. Politická Ekonomie, 2022, 70 (6). [Paper link](https://doi.org/10.1016/j.eneco.2022.105911), [Replication code and data]().
      - Janda, K., Kristoufek, L. and Zhang, B., (2022). Return and volatility spillovers between Chinese and US clean energy related stocks. Energy Economics, p.105911. [Paper link](https://polek.vse.cz/artkey/pol-202206-0003_estimation-of-green-bond-premiums-on-the-chinese-secondary-market.php?back=%2Fjel.php), [Replication code and data]().
      
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
